#!/usr/bin/python
# -*- coding: utf-8 -*-

#
#   Register data from datasheet PDF
#   Extracted from Eastron_SDM630.csv
#

from grugbus.registers import *

def MakeRegisters():
    return (
    RegFloat( 4,   0, 1, 'phase_1_line_to_neutral_volts'    , 1, 'V'      , 'float', 0, 'Phase 1 line to neutral volts'    , ''),
    RegFloat( 4,   2, 1, 'phase_2_line_to_neutral_volts'    , 1, 'V'      , 'float', 0, 'Phase 2 line to neutral volts'    , ''),
    RegFloat( 4,   4, 1, 'phase_3_line_to_neutral_volts'    , 1, 'V'      , 'float', 0, 'Phase 3 line to neutral volts'    , ''),
    RegFloat( 4,   6, 1, 'phase_1_current'                  , 1, 'A'      , 'float', 3, 'Phase 1 current'                  , ''),
    RegFloat( 4,   8, 1, 'phase_2_current'                  , 1, 'A'      , 'float', 3, 'Phase 2 current'                  , ''),
    RegFloat( 4,  10, 1, 'phase_3_current'                  , 1, 'A'      , 'float', 3, 'Phase 3 current'                  , ''),
    RegFloat( 4,  12, 1, 'phase_1_power'                    , 1, 'W'      , 'float', 0, 'Phase 1 power'                    , ''),
    RegFloat( 4,  14, 1, 'phase_2_power'                    , 1, 'W'      , 'float', 0, 'Phase 2 power'                    , ''),
    RegFloat( 4,  16, 1, 'phase_3_power'                    , 1, 'W'      , 'float', 0, 'Phase 3 power'                    , ''),
    RegFloat( 4,  18, 1, 'phase_1_volt_amps'                , 1, 'VA'     , 'float', 0, 'Phase 1 volt amps'                , ''),
    RegFloat( 4,  20, 1, 'phase_2_volt_amps'                , 1, 'VA'     , 'float', 0, 'Phase 2 volt amps'                , ''),
    RegFloat( 4,  22, 1, 'phase_3_volt_amps'                , 1, 'VA'     , 'float', 0, 'Phase 3 volt amps'                , ''),
    RegFloat( 4,  24, 1, 'phase_1_reactive_power'           , 1, 'VAr'    , 'float', 0, 'Phase 1 reactive power'           , ''),
    RegFloat( 4,  26, 1, 'phase_2_reactive_power'           , 1, 'VAr'    , 'float', 0, 'Phase 2 reactive power'           , ''),
    RegFloat( 4,  28, 1, 'phase_3_reactive_power'           , 1, 'VAr'    , 'float', 0, 'Phase 3 reactive power'           , ''),
    RegFloat( 4,  30, 1, 'phase_1_power_factor'             , 1, 'None'   , 'float', 3, 'Phase 1 power factor'             , ''),
    RegFloat( 4,  32, 1, 'phase_2_power_factor'             , 1, 'None'   , 'float', 3, 'Phase 2 power factor'             , ''),
    RegFloat( 4,  34, 1, 'phase_3_power_factor'             , 1, 'None'   , 'float', 3, 'Phase 3 power factor'             , ''),
    RegFloat( 4,  36, 1, 'phase_1_phase_angle'              , 1, 'Degrees', 'float', 0, 'Phase 1 phase angle'              , ''),
    RegFloat( 4,  38, 1, 'phase_2_phase_angle'              , 1, 'Degrees', 'float', 0, 'Phase 2 phase angle'              , ''),
    RegFloat( 4,  40, 1, 'phase_3_phase_angle'              , 1, 'Degrees', 'float', 0, 'Phase 3 phase angle'              , ''),
    RegFloat( 4,  42, 1, 'average_line_to_neutral_volts'    , 1, 'V'      , 'float', 0, 'Average line to neutral volts'    , ''),
    RegFloat( 4,  46, 1, 'average_line_current'             , 1, 'A'      , 'float', 3, 'Average line current'             , ''),
    RegFloat( 4,  48, 1, 'sum_of_line_currents'             , 1, 'A'      , 'float', 3, 'Sum of line currents'             , ''),
    RegFloat( 4,  52, 1, 'total_power'                      , 1, 'W'      , 'float', 0, 'Total power'                      , ''),
    RegFloat( 4,  56, 1, 'total_volt_amps'                  , 1, 'VA'     , 'float', 0, 'Total volt amps'                  , ''),
    RegFloat( 4,  60, 1, 'total_var'                        , 1, 'VAr'    , 'float', 0, 'Total Var'                        , ''),
    RegFloat( 4,  62, 1, 'total_power_factor'               , 1, 'None'   , 'float', 3, 'Total power factor'               , ''),
    RegFloat( 4,  66, 1, 'total_phase_angle'                , 1, 'Degrees', 'float', 3, 'Total phase angle'                , ''),
    RegFloat( 4,  70, 1, 'frequency'                        , 1, 'Hz'     , 'float', 2, 'Frequency'                        , ''),
    RegFloat( 4,  72, 1, 'total_import_kwh'                 , 1, 'kWh'    , 'float', 4, 'Total Import kWh'                 , ''),
    RegFloat( 4,  74, 1, 'total_export_kwh'                 , 1, 'kWh'    , 'float', 4, 'Total Export kWh'                 , ''),
    RegFloat( 4,  76, 1, 'total_import_kvarh'               , 1, 'kVArh'  , 'float', 4, 'Total Import kVArh'               , ''),
    RegFloat( 4,  78, 1, 'total_export_kvarh'               , 1, 'kVArh'  , 'float', 4, 'Total Export kVArh'               , ''),
    RegFloat( 4,  80, 1, 'total_kvah'                       , 1, 'kVAh'   , 'float', 4, 'Total kVAh'                       , ''),
    RegFloat( 4,  82, 1, 'ah'                               , 1, 'Ah'     , 'float', 3, 'Ah'                               , ''),
    RegFloat( 4,  84, 1, 'total_power_demand'               , 1, 'W'      , 'float', 0, 'Total power demand'               , ''),
    RegFloat( 4,  86, 1, 'maximum_total_power_demand'       , 1, 'VA'     , 'float', 0, 'Maximum total power demand'       , ''),
    RegFloat( 4, 100, 1, 'total_va_demand'                  , 1, 'VA'     , 'float', 0, 'Total VA demand'                  , ''),
    RegFloat( 4, 102, 1, 'maximum_total_va_demand'          , 1, 'VA'     , 'float', 0, 'Maximum total VA demand'          , ''),
    RegFloat( 4, 104, 1, 'neutral_current_demand'           , 1, 'A'      , 'float', 3, 'Neutral current demand'           , ''),
    RegFloat( 4, 106, 1, 'maximum_neutral_current_demand'   , 1, 'A'      , 'float', 3, 'Maximum neutral current demand'   , ''),
    RegFloat( 4, 200, 1, 'line_1_to_line_2_volts'           , 1, 'V'      , 'float', 0, 'Line 1 to Line 2 volts'           , ''),
    RegFloat( 4, 202, 1, 'line_2_to_line_3_volts'           , 1, 'V'      , 'float', 0, 'Line 2 to Line 3 volts'           , ''),
    RegFloat( 4, 204, 1, 'line_3_to_line_1_volts'           , 1, 'V'      , 'float', 0, 'Line 3 to Line 1 volts'           , ''),
    RegFloat( 4, 206, 1, 'average_line_to_line_volts'       , 1, 'V'      , 'float', 0, 'Average line to line volts'       , ''),
    RegFloat( 4, 224, 1, 'neutral_current'                  , 1, 'A'      , 'float', 3, 'Neutral current'                  , ''),
    RegFloat( 4, 234, 1, 'phase_1_l_n_volts_thd'            , 1, '%'      , 'float', 1, 'Phase 1 L/N volts THD'            , ''),
    RegFloat( 4, 236, 1, 'phase_2_l_n_volts_thd'            , 1, '%'      , 'float', 1, 'Phase 2 L/N volts THD'            , ''),
    RegFloat( 4, 238, 1, 'phase_3_l_n_volts_thd'            , 1, '%'      , 'float', 1, 'Phase 3 L/N volts THD'            , ''),
    RegFloat( 4, 240, 1, 'phase_1_current_thd'              , 1, '%'      , 'float', 1, 'Phase 1 Current THD'              , ''),
    RegFloat( 4, 242, 1, 'phase_2_current_thd'              , 1, '%'      , 'float', 1, 'Phase 2 Current THD'              , ''),
    RegFloat( 4, 244, 1, 'phase_3_current_thd'              , 1, '%'      , 'float', 1, 'Phase 3 Current THD'              , ''),
    RegFloat( 4, 248, 1, 'average_line_to_neutral_volts_thd', 1, '%'      , 'float', 1, 'Average line to neutral volts THD', ''),
    RegFloat( 4, 250, 1, 'average_line_current_thd'         , 1, '%'      , 'float', 1, 'Average line current THD'         , ''),
    RegFloat( 4, 258, 1, 'phase_1_current_demand'           , 1, 'A'      , 'float', 3, 'Phase 1 current demand'           , ''),
    RegFloat( 4, 260, 1, 'phase_2_current_demand'           , 1, 'A'      , 'float', 3, 'Phase 2 current demand'           , ''),
    RegFloat( 4, 262, 1, 'phase_3_current_demand'           , 1, 'A'      , 'float', 3, 'Phase 3 current demand'           , ''),
    RegFloat( 4, 264, 1, 'maximum_phase_1_current_demand'   , 1, 'A'      , 'float', 3, 'Maximum phase 1 current demand'   , ''),
    RegFloat( 4, 266, 1, 'maximum_phase_2_current_demand'   , 1, 'A'      , 'float', 3, 'Maximum phase 2 current demand'   , ''),
    RegFloat( 4, 268, 1, 'maximum_phase_3_current_demand'   , 1, 'A'      , 'float', 3, 'Maximum phase 3 current demand'   , ''),
    RegFloat( 4, 334, 1, 'line_1_to_line_2_volts_thd'       , 1, '%'      , 'float', 1, 'Line 1 to line 2 volts THD'       , ''),
    RegFloat( 4, 336, 1, 'line_2_to_line_3_volts_thd'       , 1, '%'      , 'float', 1, 'Line 2 to line 3 volts THD'       , ''),
    RegFloat( 4, 338, 1, 'line_3_to_line_1_volts_thd'       , 1, '%'      , 'float', 1, 'Line 3 to line 1 volts THD'       , ''),
    RegFloat( 4, 340, 1, 'average_line_to_line_volts_thd'   , 1, '%'      , 'float', 1, 'Average line to line volts THD'   , ''),
    RegFloat( 4, 342, 1, 'total_kwh'                        , 1, 'kWh'    , 'float', 3, 'Total kWh'                        , ''),
    RegFloat( 4, 344, 1, 'total_kvarh'                      , 1, 'kVArh'  , 'float', 3, 'Total kVArh'                      , ''),
    RegFloat( 4, 346, 1, 'l1_import_kwh'                    , 1, 'kWh'    , 'float', 3, 'L1 import kWh'                    , ''),
    RegFloat( 4, 348, 1, 'l2_import_kwh'                    , 1, 'kWh'    , 'float', 3, 'L2 import kWh'                    , ''),
    RegFloat( 4, 350, 1, 'l3_import_kwh'                    , 1, 'kWh'    , 'float', 3, 'L3 import kWh'                    , ''),
    RegFloat( 4, 352, 1, 'l1_export_kwh'                    , 1, 'kWh'    , 'float', 3, 'L1 export kWh'                    , ''),
    RegFloat( 4, 354, 1, 'l2_export_kwh'                    , 1, 'kWh'    , 'float', 3, 'L2 export kWh'                    , ''),
    RegFloat( 4, 356, 1, 'l3_export_kwh'                    , 1, 'kWh'    , 'float', 3, 'L3 export kWh'                    , ''),
    RegFloat( 4, 358, 1, 'l1_total_kwh'                     , 1, 'kWh'    , 'float', 3, 'L1 total kWh'                     , ''),
    RegFloat( 4, 360, 1, 'l2_total_kwh'                     , 1, 'kWh'    , 'float', 3, 'L2 total kWh'                     , ''),
    RegFloat( 4, 362, 1, 'l3_total_kwh'                     , 1, 'kWh'    , 'float', 3, 'L3 total kWh'                     , ''),
    RegFloat( 4, 364, 1, 'l1_import_kvarh'                  , 1, 'kVArh'  , 'float', 3, 'L1 import kVArh'                  , ''),
    RegFloat( 4, 366, 1, 'l2_import_kvarh'                  , 1, 'kVArh'  , 'float', 3, 'L2 import kVArh'                  , ''),
    RegFloat( 4, 368, 1, 'l3_import_kvarh'                  , 1, 'kVArh'  , 'float', 3, 'L3 import kVArh'                  , ''),
    RegFloat( 4, 370, 1, 'l1_export_kvarh'                  , 1, 'kVArh'  , 'float', 3, 'L1 export kVArh'                  , ''),
    RegFloat( 4, 372, 1, 'l2_export_kvarh'                  , 1, 'kVArh'  , 'float', 3, 'L2 export kVArh'                  , ''),
    RegFloat( 4, 374, 1, 'l3_export_kvarh'                  , 1, 'kVArh'  , 'float', 3, 'L3 export kVArh'                  , ''),
    RegFloat( 4, 376, 1, 'l1_total_kvarh'                   , 1, 'kVArh'  , 'float', 3, 'L1 total kVArh'                   , ''),
    RegFloat( 4, 378, 1, 'l2_total_kvarh'                   , 1, 'kVArh'  , 'float', 3, 'L2 total kVArh'                   , ''),
    RegFloat( 4, 380, 1, 'l3_total_kvarh'                   , 1, 'kVArh'  , 'float', 3, 'L3 total kVArh'                   , ''))
if __name__ == "__main__":
    MakeRegisters()

